#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.v2.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Management.v2;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Management.v2.Pages;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\ManagementPage.cshtml"
  
    Layout = new LayoutPage(Title);
    var version = $"v{GlobalConfigurationExtension.FileSuffix().Replace("_", ".")}";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 14 "..\..\Pages\ManagementPage.cshtml"
   Write(Html.RenderPartial(new Partials.ManagementSidebarPartial(Support.ManagementSidebarItemCollection.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <div class=\"visible-md-block vi" +
"sible-lg-block\">\r\n            Select a queue name from the menu on the left to s" +
"ee the jobs available.\r\n        </div>\r\n    </div>\r\n\r\n    ");


            
            #line 22 "..\..\Pages\ManagementPage.cshtml"
Write(Html.RenderPartial(new Partials.ClientResources()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
