#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.v2.Pages
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Pages\ManagementBasePage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard.Management.v2;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard.Management.v2.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard.Management.v2.Support;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementBasePage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Pages\ManagementBasePage.cshtml"
  
	Layout = new LayoutPage(ManagementPage.Title);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n\t<div class=\"col-md-3\">\r\n\t\t");


            
            #line 15 "..\..\Pages\ManagementBasePage.cshtml"
Write(Html.RenderPartial(new Partials.ManagementSidebarPartial(ManagementSidebarItemCollection.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</div>\r\n\t<div class=\"col-md-9 accordion job-panels\">\r\n");


            
            #line 18 "..\..\Pages\ManagementBasePage.cshtml"
 		foreach (var sectionKey in jobSections.Keys)
		{
			var scrubbedSection = sectionKey.ScrubURL();
			var expanded = jobSections.Keys.First() == sectionKey;

			var headingCollapsed = expanded ? "" : "collapsed";
			var ariaExpaneded = expanded ? "true" : "false";
			var panelCollapsed = expanded ? "collapse in" : "collapse";

			if (jobSections.Count > 1)
			{


            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<div class=\"panel panel-success card wrapper-panel\" data-id=\"");


            
            #line 30 "..\..\Pages\ManagementBasePage.cshtml"
                                                             Write($"section_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t<div id=\"");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
          Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-heading card-header ");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                   Write(headingCollapsed);

            
            #line default
            #line hidden
WriteLiteral(" collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                                                     Write($"#section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                                                                                                              Write(ariaExpaneded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-controls=\"");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                                                                                                                                              Write($"section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t<h4 class=\"panel-title\">");


            
            #line 32 "..\..\Pages\ManagementBasePage.cshtml"
                         Write(sectionKey);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div id=\"");


            
            #line 34 "..\..\Pages\ManagementBasePage.cshtml"
          Write($"section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 34 "..\..\Pages\ManagementBasePage.cshtml"
                                                                         Write(panelCollapsed);

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 34 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                         Write(ariaExpaneded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 34 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                           Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" data-parent=\"#jobsAccordion\">\r\n\t\t\t\t\t\t");


            
            #line 35 "..\..\Pages\ManagementBasePage.cshtml"
 Write(Html.RenderPartial(new Partials.PanelPartial(scrubbedSection, jobs.Where(j => j.SectionTitle == sectionKey).ToList())));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n");


            
            #line 38 "..\..\Pages\ManagementBasePage.cshtml"
			}
			else
			{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t<h1 class=\"page-header single-section\">");


            
            #line 41 "..\..\Pages\ManagementBasePage.cshtml"
                                      Write(sectionKey);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n");



WriteLiteral("\t\t\t\t<div id=\"");


            
            #line 42 "..\..\Pages\ManagementBasePage.cshtml"
         Write($"section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 42 "..\..\Pages\ManagementBasePage.cshtml"
                                                                        Write(panelCollapsed);

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 42 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                        Write(ariaExpaneded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 42 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                          Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" data-parent=\"#jobsAccordion\">\r\n\t\t\t\t\t");


            
            #line 43 "..\..\Pages\ManagementBasePage.cshtml"
Write(Html.RenderPartial(new Partials.PanelPartial(scrubbedSection, jobs.Where(j => j.SectionTitle == sectionKey).ToList())));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n");


            
            #line 45 "..\..\Pages\ManagementBasePage.cshtml"
			}
		}

            
            #line default
            #line hidden
WriteLiteral("\t</div>\r\n\r\n\t");


            
            #line 49 "..\..\Pages\ManagementBasePage.cshtml"
Write(Html.RenderPartial(new Partials.ClientResources()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
