#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.v2.Pages.Partials
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Pages\Partials\ClientResources.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\Partials\ClientResources.cshtml"
    using Hangfire.Dashboard.Management.v2;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ClientResources : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n\r\n");





            
            #line 7 "..\..\Pages\Partials\ClientResources.cshtml"
  
    var cssUrl = Url.To(GlobalConfigurationExtension.GetURL(GlobalConfigurationExtension.ManagementUrlType.Css));
    var jsUrl = Url.To(GlobalConfigurationExtension.GetURL(GlobalConfigurationExtension.ManagementUrlType.JsInit));
    var jsBundleUrl = Url.To(GlobalConfigurationExtension.GetURL(GlobalConfigurationExtension.ManagementUrlType.JsBundle));


    var version = $"v{GlobalConfigurationExtension.FileSuffix().Replace("_", ".")}";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div id=\"hdmConfig\" data-hdmjsbundleurl=\"");


            
            #line 16 "..\..\Pages\Partials\ClientResources.cshtml"
                                    Write(jsBundleUrl);

            
            #line default
            #line hidden
WriteLiteral("\" data-version=\"");


            
            #line 16 "..\..\Pages\Partials\ClientResources.cshtml"
                                                                Write(version);

            
            #line default
            #line hidden
WriteLiteral("\"></div>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"");


            
            #line 17 "..\..\Pages\Partials\ClientResources.cshtml"
                                        Write(cssUrl);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n<script src=\"");


            
            #line 18 "..\..\Pages\Partials\ClientResources.cshtml"
        Write(jsUrl);

            
            #line default
            #line hidden
WriteLiteral("\"></script>");


        }
    }
}
#pragma warning restore 1591
