#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.v2.Pages.Partials
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class CronExpressionBuilder : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("<div class=\"cron-expression-builder\">\r\n    <div>\r\n        <!-- Nav tabs -->\r\n    " +
"    <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n            <li role=\"presentation" +
"\" class=\"active\">\r\n                <a href=\"#minute\" aria-controls=\"minute\" role" +
"=\"tab\" data-toggle=\"tab\">Minute</a>\r\n            </li>\r\n            <li role=\"pr" +
"esentation\">\r\n                <a href=\"#hour\" aria-controls=\"hour\" role=\"tab\" da" +
"ta-toggle=\"tab\">Hour</a>\r\n            </li>\r\n            <li role=\"presentation\"" +
">\r\n                <a href=\"#day\" aria-controls=\"day\" role=\"tab\" data-toggle=\"ta" +
"b\">Day</a>\r\n            </li>\r\n            <li role=\"presentation\">\r\n           " +
"     <a href=\"#month\" aria-controls=\"month\" role=\"tab\" data-toggle=\"tab\">Month</" +
"a>\r\n            </li>\r\n            <li role=\"presentation\">\r\n                <a " +
"href=\"#week\" aria-controls=\"week\" role=\"tab\" data-toggle=\"tab\">Week</a>\r\n       " +
"     </li>\r\n            <!--\r\n            <li role=\"presentation\">\r\n            " +
"    <a href=\"#year\" aria-controls=\"year\" role=\"tab\" data-toggle=\"tab\">Year</a>\r\n" +
"            </li>\r\n            -->\r\n            <li role=\"presentation\">\r\n      " +
"          <a href=\"#general\" aria-controls=\"general\" role=\"tab\" data-toggle=\"tab" +
"\">Common Cron Expressions</a>\r\n            </li>\r\n            <li role=\"presenta" +
"tion\">\r\n                <a href=\"#cron\" aria-controls=\"cron\" role=\"tab\" data-tog" +
"gle=\"tab\">Cron Expression Analysis</a>\r\n            </li>\r\n        </ul>\r\n      " +
"  <!-- Tab panes -->\r\n        <div class=\"tab-content\">\r\n            <!--minute-" +
"->\r\n            <div role=\"tabpanel\" class=\"tab-pane active\" id=\"minute\">\r\n     " +
"           <div class=\"radio\">\r\n                    <label>\r\n                   " +
"     <input type=\"radio\" name=\"minuteType\" value=\"All\" checked=\"checked\">\r\n     " +
"                   Every minute (Permitted wildcard character[, - * /])\r\n       " +
"             </label>\r\n                </div>\r\n                <div class=\"radio" +
"\">\r\n                    <label>\r\n                        <input type=\"radio\" nam" +
"e=\"minuteType\" value=\"Cyclic\">\r\n                        Time range is from\r\n    " +
"                    <input type=\"number\" id=\"minuteTypeCyclic_1\" value=\"1\">\r\n   " +
"                     -\r\n                        <input type=\"number\" id=\"minuteT" +
"ypeCyclic_2\" value=\"2\">\r\n                        Minute\r\n                    </l" +
"abel>\r\n                </div>\r\n                <div class=\"radio\">\r\n            " +
"        <label>\r\n                        <input type=\"radio\" name=\"minuteType\" v" +
"alue=\"Interval\">\r\n                        Start to begin at\r\n                   " +
"     <input type=\"number\" id=\"minuteTypeInterval_1\" value=\"0\">\r\n                " +
"        and runs once every\r\n                        <input type=\"number\" id=\"mi" +
"nuteTypeInterval_2\" value=\"1\">\r\n                        minutes\r\n               " +
"     </label>\r\n                </div>\r\n                <div class=\"radio\">\r\n    " +
"                <label>\r\n                        <input type=\"radio\" name=\"minut" +
"eType\" value=\"Assigned\">\r\n                        Assigned\r\n                    " +
"</label>\r\n                </div>\r\n                <div class=\"margin-left-20\">\r\n" +
"                    <select id=\"minuteTypeAssigned_1\" data-placeholder=\"Please s" +
"elect the minute type you want to assigned...\" class=\"width-350\" multiple></sele" +
"ct>\r\n                </div>\r\n            </div>\r\n            <!--hour-->\r\n      " +
"      <div role=\"tabpanel\" class=\"tab-pane\" id=\"hour\">\r\n                <div cla" +
"ss=\"radio\">\r\n                    <label>\r\n                        <input type=\"r" +
"adio\" name=\"hourType\" value=\"All\" checked=\"checked\">\r\n                        Ev" +
"ery hour (Permitted wildcard character[, - * /])\r\n                    </label>\r\n" +
"                </div>\r\n                <div class=\"radio\">\r\n                   " +
" <label>\r\n                        <input type=\"radio\" name=\"hourType\" value=\"Cyc" +
"lic\">\r\n                        Time range is from\r\n                        <inpu" +
"t type=\"number\" id=\"hourTypeCyclic_1\" value=\"0\">\r\n                        -\r\n   " +
"                     <input type=\"number\" id=\"hourTypeCyclic_2\" value=\"2\">\r\n    " +
"                    hour\r\n                    </label>\r\n                </div>\r\n" +
"                <div class=\"radio\">\r\n                    <label>\r\n              " +
"          <input type=\"radio\" name=\"hourType\" value=\"Interval\">\r\n               " +
"         Start to begin at\r\n                        <input type=\"number\" id=\"hou" +
"rTypeInterval_1\" value=\"0\">\r\n                        and runs once every\r\n      " +
"                  <input type=\"number\" id=\"hourTypeInterval_2\" value=\"1\">\r\n     " +
"                   hours\r\n                    </label>\r\n                </div>\r\n" +
"                <div class=\"radio\">\r\n                    <label>\r\n              " +
"          <input type=\"radio\" name=\"hourType\" value=\"Assigned\">\r\n               " +
"         Assigned\r\n                    </label>\r\n                </div>\r\n       " +
"         <div class=\"margin-left-20\">\r\n                    <select id=\"hourTypeA" +
"ssigned_1\" data-placeholder=\"Please select the hour type you want to assigned..." +
"\" class=\"width-350\" multiple></select>\r\n                </div>\r\n            </di" +
"v>\r\n\r\n            <!--day-->\r\n            <div role=\"tabpanel\" class=\"tab-pane\" " +
"id=\"day\">\r\n                <div class=\"radio\">\r\n                    <label>\r\n   " +
"                     <input type=\"radio\" name=\"dayType\" value=\"All\" checked=\"che" +
"cked\">\r\n                        Daily (Permitted wildcard character[, - * /])\r\n " +
"                   </label>\r\n                </div>\r\n                <div class=" +
"\"radio\">\r\n                    <label>\r\n                        <input type=\"radi" +
"o\" name=\"dayType\" value=\"Cyclic\">\r\n                        Time range is from\r\n " +
"                       <input type=\"number\" id=\"dayTypeCyclic_1\" value=\"1\">\r\n   " +
"                     -\r\n                        <input type=\"number\" id=\"dayType" +
"Cyclic_2\" value=\"2\">\r\n                        day\r\n                    </label>\r" +
"\n                </div>\r\n                <div class=\"radio\">\r\n                  " +
"  <label>\r\n                        <input type=\"radio\" name=\"dayType\" value=\"Int" +
"erval\">\r\n                        Start to begin at\r\n                        <inp" +
"ut type=\"number\" id=\"dayTypeInterval_1\" value=\"1\">\r\n                        day " +
"and runs once every\r\n                        <input type=\"number\" id=\"dayTypeInt" +
"erval_2\" value=\"1\">\r\n                        days\r\n                    </label>\r" +
"\n                </div>\r\n                <div class=\"radio\">\r\n                  " +
"  <label>\r\n                        <input type=\"radio\" name=\"dayType\" value=\"Ass" +
"igned\">\r\n                        Assigned\r\n                    </label>\r\n       " +
"         </div>\r\n                <div class=\"margin-left-20\">\r\n                 " +
"   <select id=\"dayTypeAssigned_1\" data-placeholder=\"Please select the day type y" +
"ou want to assigned...\" class=\"width-350\" multiple></select>\r\n                </" +
"div>\r\n                <!--<div class=\"radio\">\r\n                        <label>\r\n" +
"                            <input type=\"radio\" name=\"dayType\" value=\"NotAssigne" +
"d\">\r\n                            Not specify\r\n                        </label>\r\n" +
"                    </div>\r\n                    <div class=\"radio\">\r\n           " +
"             <label>\r\n                            <input type=\"radio\" name=\"dayT" +
"ype\" value=\"RecentDays\">\r\n                            per month\r\n               " +
"             <input type=\"number\" id=\"dayTypeRecentDays_1\" value=\"1\">\r\n         " +
"                   The nearest working day\r\n                        </label>\r\n  " +
"                  </div>\r\n                    <div class=\"radio\">\r\n             " +
"           <label>\r\n                            <input type=\"radio\" name=\"dayTyp" +
"e\" value=\"LastDayOfMonth\">\r\n                            Last day of the month\r\n " +
"                       </label>\r\n                    </div>\r\n                   " +
" <div class=\"radio\">\r\n                        <label>\r\n                         " +
"   <input type=\"radio\" name=\"dayType\" value=\"LastDayOfMonthRecentDays\">\r\n       " +
"                     Last business day of the month\r\n                        </l" +
"abel>\r\n                    </div>-->\r\n            </div>\r\n\r\n            <!--mont" +
"h-->\r\n            <div role=\"tabpanel\" class=\"tab-pane\" id=\"month\">\r\n           " +
"     <div class=\"radio\">\r\n                    <label>\r\n                        <" +
"input type=\"radio\" name=\"monthType\" value=\"All\" checked=\"checked\">\r\n            " +
"            Monthly (Permitted wildcard character[, - * /])\r\n                   " +
" </label>\r\n                </div>\r\n                <div class=\"radio\">\r\n        " +
"            <label>\r\n                        <input type=\"radio\" name=\"monthType" +
"\" value=\"Cyclic\">\r\n                        Time range is from\r\n                 " +
"       <input type=\"number\" id=\"monthTypeCyclic_1\" value=\"1\">\r\n                 " +
"       -\r\n                        <input type=\"number\" id=\"monthTypeCyclic_2\" va" +
"lue=\"2\">\r\n                        month\r\n                    </label>\r\n         " +
"       </div>\r\n                <div class=\"radio\">\r\n                    <label>\r" +
"\n                        <input type=\"radio\" name=\"monthType\" value=\"Interval\">\r" +
"\n                        Start to begin at\r\n                        <input type=" +
"\"number\" id=\"monthTypeInterval_1\" value=\"1\">\r\n                        month and " +
"runs once every\r\n                        <input type=\"number\" id=\"monthTypeInter" +
"val_2\" value=\"1\">\r\n                        months\r\n                    </label>\r" +
"\n                </div>\r\n                <div class=\"radio\">\r\n                  " +
"  <label>\r\n                        <input type=\"radio\" name=\"monthType\" value=\"A" +
"ssigned\">\r\n                        Assigned\r\n                    </label>\r\n     " +
"           </div>\r\n                <div class=\"margin-left-20\">\r\n               " +
"     <select id=\"monthTypeAssigned_1\" data-placeholder=\"Please select the month " +
"type you want to assigned...\" class=\"width-350\" multiple></select>\r\n            " +
"    </div>\r\n                <!--<div class=\"radio\">\r\n                        <la" +
"bel>\r\n                            <input type=\"radio\" name=\"monthType\" value=\"No" +
"tAssigned\">\r\n                            Not specify\r\n                        </" +
"label>\r\n                    </div>-->\r\n            </div>\r\n\r\n            <!--wee" +
"k-->\r\n            <div role=\"tabpanel\" class=\"tab-pane\" id=\"week\">\r\n            " +
"    <div class=\"radio\">\r\n                    <label>\r\n                        <i" +
"nput type=\"radio\" name=\"weekType\" value=\"All\" checked=\"checked\">\r\n              " +
"          Weekly (Permitted wildcard character[, - * /])\r\n                    </" +
"label>\r\n                </div>\r\n                <div class=\"radio\">\r\n           " +
"         <label>\r\n                        <input type=\"radio\" name=\"weekType\" va" +
"lue=\"Cyclic\">\r\n                        Time range is from\r\n                     " +
"   <input type=\"number\" id=\"weekTypeCyclic_1\" value=\"1\">\r\n                      " +
"  -\r\n                        <input type=\"number\" id=\"weekTypeCyclic_2\" value=\"2" +
"\">\r\n                        week\r\n                    </label>\r\n                " +
"</div>\r\n                <div class=\"radio\">\r\n                    <label>\r\n      " +
"                  <input type=\"radio\" name=\"weekType\" value=\"WeeksOfWeek\">\r\n    " +
"                    Start to run at the\r\n                        <input type=\"nu" +
"mber\" id=\"weekTypeWeeksOfWeek_1\" value=\"1\">\r\n                        and the day" +
" of the week is\r\n                        <input type=\"number\" id=\"weekTypeWeeksO" +
"fWeek_2\" value=\"1\">\r\n                    </label>\r\n                </div>\r\n     " +
"           <div class=\"radio\">\r\n                    <label>\r\n                   " +
"     <input type=\"radio\" name=\"weekType\" value=\"Assigned\">\r\n                    " +
"    Assigned\r\n                    </label>\r\n                </div>\r\n            " +
"    <div class=\"margin-left-20\">\r\n                    <select id=\"weekTypeAssign" +
"ed_1\" data-placeholder=\"Please select the week type you want to assigned...\" cla" +
"ss=\"width-350\" multiple></select>\r\n                </div>\r\n                <div " +
"class=\"d-none\">\r\n                    <div class=\"radio\">\r\n                      " +
"  <label>\r\n                            <input type=\"radio\" name=\"weekType\" value" +
"=\"NotAssigned\">\r\n                            Not specify\r\n                      " +
"  </label>\r\n                    </div>\r\n                    <div class=\"radio\">\r" +
"\n                        <label>\r\n                            <input type=\"radio" +
"\" name=\"weekType\" value=\"LastWeekOfMonth\">\r\n                            Last wee" +
"k of the month\r\n                            <input type=\"number\" id=\"weekTypeLas" +
"tWeekOfMonth_1\" value=\"1\">\r\n                        </label>\r\n                  " +
"  </div>\r\n                </div>\r\n            </div>\r\n\r\n\r\n            <div role=" +
"\"tabpanel\" class=\"tab-pane d-none\" id=\"year\">\r\n                <div class=\"radio" +
"\">\r\n                    <label>\r\n                        <input type=\"radio\" nam" +
"e=\"yearType\" value=\"All\" checked=\"checked\">\r\n                        Wildcard al" +
"lowed per year [, - * /]\r\n                    </label>\r\n                </div>\r\n" +
"                <div class=\"radio\">\r\n                    <label>\r\n              " +
"          <input type=\"radio\" name=\"yearType\" value=\"NotAssigned\">\r\n            " +
"            Not specify\r\n                    </label>\r\n                </div>\r\n " +
"               <div class=\"radio\">\r\n                    <label>\r\n               " +
"         <input type=\"radio\" name=\"yearType\" value=\"Cyclic\">\r\n                  " +
"      Cycle from\r\n                        <input type=\"number\" id=\"yearTypeCycli" +
"c_1\" value=\"2015\">\r\n                        -\r\n                        <input ty" +
"pe=\"number\" id=\"yearTypeCyclic_2\" value=\"2299\">\r\n                        year\r\n " +
"                   </label>\r\n                </div>\r\n                <div class=" +
"\"radio\">\r\n                    <label>\r\n                        <input type=\"radi" +
"o\" name=\"yearType\" value=\"Assigned\">\r\n                        Specified\r\n       " +
"             </label>\r\n                </div>\r\n                <div class=\"margi" +
"n-left-20\">\r\n                    <select id=\"yearTypeAssigned_1\" data-placeholde" +
"r=\"Select specified year...\" class=\"width-350\" multiple></select>\r\n             " +
"   </div>\r\n            </div>\r\n            <!--Common Cron Expressions-->\r\n     " +
"       <div role=\"tabpanel\" class=\"tab-pane cron-examples\" id=\"general\">\r\n      " +
"          <ul class=\"nav nav-pills nav-stacked\">\r\n                    <li><a><di" +
"v class=\"d-flex\" data-cronvalue=\"* * * * *\"><div class=\"col-sm-9\">Every minute</" +
"div><div class=\"col-sm-3\">* * * * *</div></div></a></li>\r\n                    <l" +
"i><a><div class=\"d-flex\" data-cronvalue=\"0 * * * *\"><div class=\"col-sm-9\">Every " +
"hour  </div><div class=\"col-sm-3\">0 * * * *</div></div></a></li>\r\n              " +
"      <li><a><div class=\"d-flex\" data-cronvalue=\"0 0 * * *\"><div class=\"col-sm-9" +
"\">Daily       </div><div class=\"col-sm-3\">0 0 * * *</div></div></a></li>\r\n      " +
"              <li><a><div class=\"d-flex\" data-cronvalue=\"0 0 * * 1\"><div class=\"" +
"col-sm-9\">Weekly      </div><div class=\"col-sm-3\">0 0 * * 1</div></div></a></li>" +
"\r\n                    <li><a><div class=\"d-flex\" data-cronvalue=\"0 0 1 * *\"><div" +
" class=\"col-sm-9\">Monthly     </div><div class=\"col-sm-3\">0 0 1 * *</div></div><" +
"/a></li>\r\n                    <li><a><div class=\"d-flex\" data-cronvalue=\"0 0 1 1" +
" *\"><div class=\"col-sm-9\">Annually    </div><div class=\"col-sm-3\">0 0 1 1 *</div" +
"></div></a></li>\r\n                </ul>\r\n                <br />\r\n               " +
" <div><b>Commonly used Example</b></div>\r\n                <ul class=\"nav nav-pil" +
"ls nav-stacked\">\r\n                    <li><a><div class=\"d-flex\" data-cronvalue=" +
"\"0 10 * * * ?\"><div class=\"col-sm-9\">Run once every hour after 10 minutes</div><" +
"div class=\"col-sm-3\">0 10 * * * ?</div></div></a></li>\r\n                    <li>" +
"<a><div class=\"d-flex\" data-cronvalue=\"0 0/32 8,12 * * ?\"><div class=\"col-sm-9\">" +
"Run once at 8:32 am and 12:32 pm every day</div><div class=\"col-sm-3\">0 0/32 8,1" +
"2 * * ?</div></div></a></li>\r\n                    <li><a><div class=\"d-flex\" dat" +
"a-cronvalue=\"0 0/2 * * * ?\"><div class=\"col-sm-9\">Run once every 2 minutes</div>" +
"<div class=\"col-sm-3\">0 0/2 * * * ?</div></div></a></li>\r\n                    <l" +
"i><a><div class=\"d-flex\" data-cronvalue=\"0 0 12 * * ?\"><div class=\"col-sm-9\">Run" +
" once at 12:00 pm every day</div><div class=\"col-sm-3\">0 0 12 * * ?</div></div><" +
"/a></li>\r\n                    <li><a><div class=\"d-flex\" data-cronvalue=\"0 15 10" +
" ? * *\"><div class=\"col-sm-9\">Run once at 10:15 am every day</div><div class=\"co" +
"l-sm-3\">0 15 10 ? * *</div></div></a></li>\r\n                    <li><a><div clas" +
"s=\"d-flex\" data-cronvalue=\"0 15 10 * * ?\"><div class=\"col-sm-9\">Run once at 10:1" +
"5 am every day</div><div class=\"col-sm-3\">0 15 10 * * ?</div></div></a></li>\r\n\r\n" +
"                    <li><a><div class=\"d-flex\" data-cronvalue=\"0 15 10 * * ? *\">" +
"<div class=\"col-sm-9\">Run once at 10:15 am every day</div><div class=\"col-sm-3\">" +
"0 15 10 * * ? *</div></div></a></li>\r\n                    <li><a><div class=\"d-f" +
"lex\" data-cronvalue=\"0 15 10 * * ? 2005\"><div class=\"col-sm-9\">Run once at 10:15" +
" am every day on 2005</div><div class=\"col-sm-3\">0 15 10 * * ? 2005</div></div><" +
"/a></li>\r\n                    <li><a><div class=\"d-flex\" data-cronvalue=\"0 * 14 " +
"* * ?\"><div class=\"col-sm-9\">Run once every minute between 2:00 pm and 2:59 pm e" +
"very day</div><div class=\"col-sm-3\">0 * 14 * * ?</div></div></a></li>\r\n         " +
"           <li><a><div class=\"d-flex\" data-cronvalue=\"0 0/5 14 * * ?\"><div class" +
"=\"col-sm-9\">Run once every 5 minutes between 2:00 pm and 2:59 pm every day</div>" +
"<div class=\"col-sm-3\">0 0/5 14 * * ?</div></div></a></li>\r\n                    <" +
"li><a><div class=\"d-flex\" data-cronvalue=\"0 0/5 14,18 * * ?\"><div class=\"col-sm-" +
"9\">Run once every 5 minutes between 2:00 pm and 2:59 pm and between 6:00 pm and " +
"6:59 pm every day</div><div class=\"col-sm-3\">0 0/5 14,18 * * ?</div></div></a></" +
"li>\r\n                    <li><a><div class=\"d-flex\" data-cronvalue=\"0 0-5 14 * *" +
" ?\"><div class=\"col-sm-9\">Run once every minute between 2:00 pm and 2:05 pm ever" +
"y day</div><div class=\"col-sm-3\">0 0-5 14 * * ?</div></div></a></li>\r\n          " +
"          <li><a><div class=\"d-flex\" data-cronvalue=\"0 10,44 14 ? 3 WED\"><div cl" +
"ass=\"col-sm-9\">Run once at 2:10 pm and 2:44 pm every Wednesday on March every ye" +
"ar</div><div class=\"col-sm-3\">0 10,44 14 ? 3 WED</div></div></a></li>\r\n         " +
"           <li><a><div class=\"d-flex\" data-cronvalue=\"0 15 10 ? * MON-FRI\"><div " +
"class=\"col-sm-9\">Run once at 10:15 am from Monday to Friday</div><div class=\"col" +
"-sm-3\">0 15 10 ? * MON-FRI</div></div></a></li>\r\n                    <li><a><div" +
" class=\"d-flex\" data-cronvalue=\"0 15 10 15 * ?\"><div class=\"col-sm-9\">Run once a" +
"t 10:15 am on the 15th day of each month</div><div class=\"col-sm-3\">0 15 10 15 *" +
" ?</div></div></a></li>\r\n                    <li><a><div class=\"d-flex\" data-cro" +
"nvalue=\"0 15 10 L * ?\"><div class=\"col-sm-9\">Run once at 10:15 am on the last da" +
"y of each month</div><div class=\"col-sm-3\">0 15 10 L * ?</div></div></a></li>\r\n " +
"                   <li><a><div class=\"d-flex\" data-cronvalue=\"0 15 10 ? * 6L\"><d" +
"iv class=\"col-sm-9\">Run once at 10:15 am on the last Friday of each month</div><" +
"div class=\"col-sm-3\">0 15 10 ? * 6L</div></div></a></li>\r\n                    <l" +
"i><a><div class=\"d-flex\" data-cronvalue=\"0 15 10 ? * 6L 2002-2005\"><div class=\"c" +
"ol-sm-9\">Run once at 10:15 am on the last Friday of each month between 2002 to 2" +
"005</div><div class=\"col-sm-3\">0 15 10 ? * 6L 2002-2005</div></div></a></li>\r\n  " +
"                  <li><a><div class=\"d-flex\" data-cronvalue=\"0 15 10 ? * 6#3\"><d" +
"iv class=\"col-sm-9\">Run once at 10:15 am on the third Friday of each month</div>" +
"<div class=\"col-sm-3\">0 15 10 ? * 6#3</div></div></a></li>\r\n                    " +
"<li><a><div class=\"d-flex\" data-cronvalue=\"0 0 12 1/5 * ?\"><div class=\"col-sm-9\"" +
">Run once at 12:00 pm every 5 days since the first day of each month</div><div c" +
"lass=\"col-sm-3\">0 0 12 1/5 * ?</div></div></a></li>\r\n                    <li><a>" +
"<div class=\"d-flex\" data-cronvalue=\"0 11 11 11 11 ?\"><div class=\"col-sm-9\">Run o" +
"nce at 11:11 am on every November 11th</div><div class=\"col-sm-3\">0 11 11 11 11 " +
"?</div></div></a></li>\r\n                </ul>\r\n                <br />\r\n\r\n\r\n     " +
"           <br /><br />\r\n\r\n                Run once at 11:11 am on every Novembe" +
"r 11th：0 0 0 * * ?<br />\r\n                At midnight every Monday：0 0 0 ? * MON" +
" or 0 0 0 ? * 2 (Note:1=SUN,2=MON,3=TUE,4=WED,5=THU,6=FRI,7=SAT)<br />\r\n        " +
"        At midnight on the first day of each month： 0 0 0 1 * ?<br />\r\n         " +
"       At midnight on January 1st every year：0 0 0 1 1 ?or 0 0 0 1 JAN ?(Note:Th" +
"e months from 1 to 12 represents JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OC" +
"T, NOV, DEC)<br />\r\n                At midnight on August 1st, 2046：0 0 0 1 8 ? " +
"2046<br />\r\n\r\n                Run once every 5 minutes：*/5 * * * * ?<br />\r\n\r\n  " +
"              Run once every minute：0 */1 * * * ?<br />\r\n\r\n                Run o" +
"nce at 11:00 pm every day：0 0 23 * * ?<br />\r\n\r\n                Run once at 1:00" +
" am every day：0 0 1 * * ?<br />\r\n\r\n                Run once at 1:00 am on the fi" +
"rst day of each month：0 0 1 1 * ?<br />\r\n\r\n                Run once at 11:00 pm " +
"on the last day of each month：0 0 23 L * ?<br />\r\n\r\n                Run once at " +
"1:00 am on every Sunday of each week：0 0 1 ? * L<br />\r\n\r\n                Run on" +
"ce at 26, 29, 33 minutes every hour：0 26,29,33 * * * ?<br />\r\n\r\n                " +
"Run once at 12:00 am(midnight), 1:00 pm, 6:00 pm and 9:00 pm every day：0 0 0,13," +
"18,21 * * ?<br />\r\n\r\n                Run once every 5 minutes：0 0/5 * * * ?<br /" +
">\r\n                \"0 0 12 * * ?\" Run once at 12:00 pm every day<br />\r\n        " +
"        \"0 15 10 ? * *\" Run once at 10:15 am every day<br />\r\n                \"0" +
" 15 10 * * ?\" Run once at 10:15 am every day<br />\r\n                \"0 15 10 * *" +
" ? *\" Run once at 10:15 am every day<br />\r\n                \"0 15 10 * * ? 2005\"" +
" Run once at 10:15 am every day on 2005<br />\r\n                \"0 * 14 * * ?\" Ru" +
"n once every minute between 2:00 pm and 2:59 pm every day<br />\r\n               " +
" \"0 0/5 14 * * ?\" Run once every 5 minutes between 2:00 pm and 2:59 pm every day" +
"<br />\r\n                \"0 0/5 14,18 * * ?\" Run once every 5 minutes between 2:0" +
"0 pm and 2:59 pm and between 6:00 pm and 6:59 pm every day<br />\r\n              " +
"  \"0 0-5 14 * * ?\" Run once every minute between 2:00 pm and 2:05 pm every day<b" +
"r />\r\n                \"0 10,44 14 ? 3 WED\" Run once at 2:10 pm and 2:44 pm every" +
" Wednesday on March every year<br />\r\n                \"0 15 10 ? * MON-FRI\" Run " +
"once at 10:15 am from Monday to Friday<br />\r\n                \"0 15 10 15 * ?\" R" +
"un once at 10:15 am on the 15th day of each month<br />\r\n                \"0 15 1" +
"0 L * ?\" Run once at 10:15 am on the last day of each month<br />\r\n             " +
"   \"0 15 10 ? * 6L\" Run once at 10:15 am on the last Friday of each month<br />\r" +
"\n                \"0 15 10 ? * 6L 2002-2005\" Run once at 10:15 am on the last Fri" +
"day of each month between 2002 to 2005<br />\r\n                \"0 15 10 ? * 6#3\" " +
"Run once at 10:15 am on the third Friday of each month<br />\r\n            </div>" +
"\r\n\r\n            <!--Cron Expression Analysis-->\r\n            <div role=\"tabpanel" +
"\" class=\"tab-pane\" id=\"cron\">\r\n                Verified address {Url.To(\"/cron?c" +
"ron=*+*+*+*+*\")}<br /><br />\r\n                Precise to the minute in the forma" +
"t of 5 characters\r\n                <pre>\r\n                    * * * * *\r\n       " +
"             - - - - -\r\n                    | | | | |\r\n                    | | |" +
" | +----- day of week (0 - 6) (Sunday=0)\r\n                    | | | +------- mon" +
"th (1 - 12)\r\n                    | | +--------- day of month (1 - 31)\r\n         " +
"           | +----------- hour (0 - 23)\r\n                    +------------- min " +
"(0 - 59)\r\n                </pre>\r\n                Precise to the minute and seco" +
"nd in the format of 6 characters\r\n                <pre>\r\n                * * * *" +
" * *\r\n                - - - - - -\r\n                | | | | | |\r\n                " +
"| | | | | +--- day of week (0 - 6) (Sunday=0)\r\n                | | | | +----- mo" +
"nth (1 - 12)\r\n                | | | +------- day of month (1 - 31)\r\n            " +
"    | | +--------- hour (0 - 23)\r\n                | +----------- min (0 - 59)\r\n " +
"               +------------- sec (0 - 59)\r\n                </pre>\r\n            " +
"    Definition of special wildcard characters<br />\r\n                <pre>\r\n    " +
"            * It means any value. For example, if you put \"*\" at the month place" +
", it means it will happen every month. If it is placed at the day of week spot, " +
"the operation would happen every day of week;\r\n                - It means a spec" +
"ific range;\r\n                , It means adding a possible value for the same pla" +
"ce;\r\n                / The value placed before the character means the starting " +
"time and the value placed after that means the incremental value for every time;" +
"\r\n                </pre>\r\n\r\n                <b>The Cron expression includes 7 ch" +
"aracters displayed as below</b><br />\r\n                <ul class=\"list-unstyled\"" +
">\r\n                    <li>Format: [Second] [Minute] [Hour] [Day of month] [Mont" +
"h] [Week] [Year]</li>\r\n                    <li>\r\n                        <table " +
"class=\"table table-hover\">\r\n                            <tr>\r\n                  " +
"              <th>Num</th>\r\n                                <th>Description</th>" +
"\r\n                                <th>Required</th>\r\n                           " +
"     <th>Allowed values</th>\r\n                                <th>v</th>\r\n      " +
"                      </tr>\r\n                            <tr>\r\n                 " +
"               <td>1</td>\r\n                                <td>second</td>\r\n    " +
"                            <td>Yes</td>\r\n                                <td>0-" +
"59</td>\r\n                                <td>, - * /</td>\r\n                     " +
"       </tr>\r\n                            <tr>\r\n                                " +
"<td>2</td>\r\n                                <td>Minute</td>\r\n                   " +
"             <td>Yes</td>\r\n                                <td>0-59</td>\r\n      " +
"                          <td>, - * /</td>\r\n                            </tr>\r\n " +
"                           <tr>\r\n                                <td>3</td>\r\n   " +
"                             <td>hour</td>\r\n                                <td>" +
"Yes</td>\r\n                                <td>0-23</td>\r\n                       " +
"         <td>, - * /</td>\r\n                            </tr>\r\n                  " +
"          <tr>\r\n                                <td>4</td>\r\n                    " +
"            <td>day</td>\r\n                                <td>Yes</td>\r\n        " +
"                        <td>0-31</td>\r\n                                <td>, - *" +
" ? / L W</td>\r\n                            </tr>\r\n                            <t" +
"r>\r\n                                <td>5</td>\r\n                                " +
"<td>month</td>\r\n                                <td>Yes</td>\r\n                  " +
"              <td>1-12 or JAN-DEC</td>\r\n                                <td>, - " +
"* /</td>\r\n                            </tr>\r\n                            <tr>\r\n " +
"                               <td>6</td>\r\n                                <td>w" +
"eek</td>\r\n                                <td>Yes</td>\r\n                        " +
"        <td>1-7 or SUN-SAT</td>\r\n                                <td>, - * ? / L" +
" #</td>\r\n                            </tr>\r\n                            <tr>\r\n  " +
"                              <td>7</td>\r\n                                <td>ye" +
"ar</td>\r\n                                <td>No</td>\r\n                          " +
"      <td>empty or 1970-2099</td>\r\n                                <td>, - * /</" +
"td>\r\n                            </tr>\r\n                        </table>\r\n      " +
"              </li>\r\n                </ul>\r\n                <b>The description o" +
"f Wildcard character</b><br />\r\n                <ol>\r\n                    <li>Th" +
"e forward slash(/) means the incremental value. For example, \"5/15\" in the place" +
" of second show that it will run once every 15 seconds since the fifth second ev" +
"ery minute.</li>\r\n                    <li>Asterisk (*) is one of the wildcard ch" +
"aracters, which means it will accept any possible value(e.g. it means it will ru" +
"n every minute when the asterisk is set at the place of minute.).</li>\r\n        " +
"            <li>The question mark(?) means it does not include any specific valu" +
"e, so it can be set \"?\" at the place of the day of month if it does not matter w" +
"hat date it is. Letter L is the abbreviation of last. It means the operation is " +
"scheduled at the last day of month if this letter is put at the place of month. " +
"In the place of week, it is equal to 7 if letter L exits alone. Otherwise, it re" +
"presents the last day of the last week of the month. For instance, \"0L\" shows th" +
"at the operation will be triggered on Sunday of the last week for that month.</l" +
"i>\r\n                    <li>\"-\" means that users can specify the time range. For" +
" example, if the place of hour is set \"10-12\", it means that the operation will " +
"run at 10:00, 11:00, 12:00 am.</li>\r\n                    <li>Comma(,) means it c" +
"an be set to different values at the same spot of cron expression format. For ex" +
"ample, \"MON,WED,FRI\" at the place of week means the operation is set to run on M" +
"onday, Wednesday and Friday.</li>\r\n                    <li>The pound sign means " +
"that it is assigned a specific business day of the given month. \"MON#2\" in the p" +
"lace of week means the task will start to begin on the second Monday of a month." +
"</li>\r\n                    <li>L means the last one. if L is put alone at the pl" +
"ace of day of month, it means the last day of month(The number of day would be d" +
"ifferent depending on which month it is. If it is on February, it will also chec" +
"k whether it is leap year or not). The letter L is equal to \"7\" or \"SAT\". If the" +
"re is a number value before \"L\", it means it is the last instance for that numbe" +
"r value. For example, \"6L\" at the place of day of week means it is set to the la" +
"st Friday of that month.</li>\r\n                    <li>W means the closest busin" +
"ess day(Monday to Friday) to the assigned day. For instance, \"15W\" at the place " +
"of day of month means the task will be triggered to run at the closest business " +
"day to the 15th of each month. If the 15th day is Saturday, the operation will r" +
"un on recent Friday(14th day of month). If the 15th day is Sunday, the task will" +
" be triggered on next Monday(16th day of month). The task will run on the assign" +
"ed day if it is weekday(Monday to Friday). For instance, \"1W\" means it will perf" +
"orm the job on the closest weekday to the first day of each month.</li>\r\n       " +
"         </ol>\r\n                <p class=\"text-danger\">Note: \'L\' and \'W\' can be " +
"used together. \"LW\" placed at the day of month means the job will be ran at the " +
"last business day for that month.</p><br />\r\n\r\n            </div>\r\n        </div" +
">\r\n    </div>\r\n    <hr>\r\n    <div class=\"panel panel-info\">\r\n        <div class=" +
"\"panel-heading\">\r\n            <h3 class=\"panel-title\">Result</h3>\r\n        </div" +
">\r\n        <div class=\"panel-body\">\r\n            <form class=\"form-inline\">\r\n   " +
"             <div class=\"form-group\">\r\n                    <div class=\"input-gro" +
"up input-group-sm\">\r\n                        <input type=\"text\" class=\"form-cont" +
"rol\" id=\"result\" placeholder=\"Result\">\r\n                        <div class=\"inpu" +
"t-group-btn \">\r\n                            <button type=\"button\" id=\"analysis\" " +
"class=\"btn btn-default\"><span class=\"glyphicon glyphicon-ok\"></span>  &nbsp;Anal" +
"ysis</button>\r\n                        </div>\r\n                    </div>\r\n     " +
"           </div>\r\n            </form>\r\n        </div>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
