#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.v2.Pages.Partials
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
    using Hangfire.Dashboard.Management.v2;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementSidebarPartial : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n<ul class=\"nav nav-tabs hidden-md hidden-lg\">\r\n");


            
            #line 10 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
 foreach (var item in Items)
	{
		var itemValue = item(this);
		var activeClass = itemValue.Active ? "active" : "";

            
            #line default
            #line hidden
WriteLiteral("\t\t<li role=\"presentation\" class=\"");


            
            #line 14 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                            Write(activeClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t<a href=\"");


            
            #line 15 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
       Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 15 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                       Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<span class=\"pull-right\">\r\n\t\t\t\t</span>\r\n\t\t\t</a>\r\n\t\t</li>\r\n");


            
            #line 20 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n<ul class=\"nav nav-pills nav-stacked visible-md-block visible-lg-block\">\r\n" +
"");


            
            #line 23 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
 foreach (var item in Items)
	{
		var itemValue = item(this);
		var activeClass = itemValue.Active ? "active" : "";

            
            #line default
            #line hidden
WriteLiteral("\t\t<li role=\"presentation\" class=\"");


            
            #line 27 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                            Write(activeClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t<a href=\"");


            
            #line 28 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
       Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t");


            
            #line 29 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t<span class=\"pull-right\">\r\n\t\t\t\t</span>\r\n\t\t\t</a>\r\n\t\t</li>\r\n");


            
            #line 34 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


        }
    }
}
#pragma warning restore 1591
