#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Management.v2.Pages.Partials
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Pages\Partials\PanelPartial.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Management.v2;
    
    #line default
    #line hidden
    
    #line 12 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Management.v2.Metadata;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Management.v2.Pages;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Management.v2.Pages.Partials;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Management.v2.Support;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Server;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    #line 13 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    #line 14 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class PanelPartial : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");
















            
            #line 16 "..\..\Pages\Partials\PanelPartial.cshtml"
  



            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 20 "..\..\Pages\Partials\PanelPartial.cshtml"
 foreach (var job in Jobs)
{
    var id = $"{SectionName}_{job.Name.ScrubURL()}";
    var expanded = Jobs.First() == job;

    var options = new JObject();
    var qAttr = job.MethodInfo.GetCustomAttributes(true).OfType<QueueAttribute>().FirstOrDefault();
    options.Add("Queue", (qAttr == default ? "default" : qAttr.Queue).ToUpper());

    var showMDAttr = job.MethodInfo.GetCustomAttributes(true).OfType<ShowMetaDataAttribute>().FirstOrDefault();
    var showMeta = showMDAttr != default && showMDAttr.ShowOnUI;

    if (showMeta)
    {
        var retryAttr = job.MethodInfo.GetCustomAttributes(true).OfType<AutomaticRetryAttribute>().FirstOrDefault();
        if (retryAttr != default)
        {
            var ar = new JObject(){
                            { "Attempts", retryAttr.Attempts },
                            { "AllowMultiple", retryAttr.AllowMultiple },
                            { "DelaysInSeconds", (retryAttr.DelaysInSeconds != null ? JsonConvert.SerializeObject(retryAttr.DelaysInSeconds) : null) },
                            { "LogEvents", retryAttr.LogEvents },
                            { "OnAttemptsExceeded", (retryAttr.OnAttemptsExceeded == AttemptsExceededAction.Delete ? "Delete" : "Fail") }
                        };
            options.Add("AutomaticRetryAttribute", ar);
        }
    }
    var headingCollapsed = expanded ? "" : "collapsed";
    var panelCollapsed = expanded ? "collapse in" : "collapse";
    var ariaExpanded = expanded ? "true" : "false";
    var multiAllowed = job.AllowMultiple ? "hdm-multi-allowed" : "";


            
            #line default
            #line hidden
WriteLiteral("    <div class=\"panel panel-info hdm-management hdm-job-panel card ");


            
            #line 52 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                              Write(multiAllowed);

            
            #line default
            #line hidden
WriteLiteral("\" data-id=\"");


            
            #line 52 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                      Write(id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <div id=\"");


            
            #line 53 "..\..\Pages\Partials\PanelPartial.cshtml"
             Write($"heading_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-heading card-header ");


            
            #line 53 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                 Write(headingCollapsed);

            
            #line default
            #line hidden
WriteLiteral(" collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"");


            
            #line 53 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                                   Write($"#collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 53 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                                                                       Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-controls=\"");


            
            #line 53 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                                                                                                      Write($"collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <h4 class=\"panel-title\">\r\n                ");


            
            #line 55 "..\..\Pages\Partials\PanelPartial.cshtml"
           Write(job.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </h4>\r\n        </div>\r\n        <div id=\"");


            
            #line 58 "..\..\Pages\Partials\PanelPartial.cshtml"
             Write($"collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 58 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                       Write(panelCollapsed);

            
            #line default
            #line hidden
WriteLiteral(" hdm-job-container\" aria-expanded=\"");


            
            #line 58 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                         Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 58 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                          Write($"heading_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" data-parent=\"#jobsAccordion\">\r\n            <div class=\"panel-body\">\r\n          " +
"      <p>");


            
            #line 60 "..\..\Pages\Partials\PanelPartial.cshtml"
              Write(job.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 61 "..\..\Pages\Partials\PanelPartial.cshtml"
                 if (showMeta)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"well hdm-show-metadata\">\r\n                       " +
" <div class=\"col-xs-1\" role=\"button\" data-toggle=\"collapse\" href=\"");


            
            #line 64 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                     Write($"#options_collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"false\" aria-controls=\"");


            
            #line 64 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                        Write($"options_collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Click to show metadata for this job.\">\r\n                            <spa" +
"n class=\"glyphicon glyphicon-info-sign\"></span>\r\n                        </div>\r" +
"\n                        <pre class=\"col-xs-11 collapse\" aria-expanded=\"false\" i" +
"d=\"");


            
            #line 67 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                              Write($"options_collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 67 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                          Write(JsonConvert.SerializeObject(options, Formatting.Indented));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n                    </div>\r\n");


            
            #line 69 "..\..\Pages\Partials\PanelPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div class=\"panel-body\">\r\n                ");


            
            #line 72 "..\..\Pages\Partials\PanelPartial.cshtml"
           Write(Html.RenderPartial(new JobPartial(id, job)));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"panel-footer\">\r\n                ");


            
            #line 75 "..\..\Pages\Partials\PanelPartial.cshtml"
           Write(Html.RenderPartial(new ButtonPartial(id, job)));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 79 "..\..\Pages\Partials\PanelPartial.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
